###
GET http://localhost:5000/api/admin/login/A1/Sarika@123

###
GET http://localhost:5000/api/admin/internships

###
GET http://localhost:5000/api/user/profile

###
GET http://localhost:5000/api/organization
###
POST  http://localhost:5000/api/organization
Content-Type: application/json

{
  "name": "New Organization"
}